import type { MacroTimelineItem } from "../macro-timeline";
import type { MacroStudioState } from "./state";

export function generateScript(timeline: MacroTimelineItem[], state: MacroStudioState): string {
  const { leadInMs, keyDelayMs, iterations, pauseBetweenIterationsMs, triggerMode } = state;
  const lines = [
    "// Generated by dumbWASD Macro Sequencer",
    `// Trigger mode: ${triggerMode === "hold" ? "hold until release" : "execute at once"}`,
    "",
    `macro("exported-macro", () => {`,
    `  keyDelay(${keyDelayMs});`,
  ];

  if (leadInMs > 0) {
    lines.push(`  wait(${leadInMs});`);
  }

  if (iterations > 1) {
    lines.push(`  repeat(${iterations}, ({ loop }) => {`);
  }

  const indent = iterations > 1 ? "    " : "  ";
  if (timeline.length === 0) {
    lines.push(`${indent}// No timeline items recorded yet`);
  } else {
    for (const item of timeline) {
      if (item.kind === "wait") {
        lines.push(`${indent}wait(${item.durationMs});`);
      } else if (item.kind === "rumble") {
        lines.push(`${indent}rumble(${item.durationMs});`);
      } else if (item.direction === "down") {
        lines.push(`${indent}pressDown("${item.input}");`);
      } else {
        lines.push(`${indent}liftUp("${item.input}");`);
      }
    }
  }

  if (iterations > 1) {
    if (pauseBetweenIterationsMs > 0) {
      lines.push(`    if (loop < ${iterations - 1}) wait(${pauseBetweenIterationsMs});`);
    }
    lines.push("  });");
  }

  lines.push("});");
  return lines.join("\n");
}
