[profile]
name = "Default"
device_name = "Azeron Cyborg"

[[devices]]
id = "5840:4284"
vendor_id = 5840
product_id = 4284
name = "Azeron Keypad"
raw_name = "Azeron LTD Azeron Keypad"
layout = "azeron-cyborg"
device_kind = "azeron"
active_binding_preset = ""
binding_presets = []

[[devices]]
id = ""
vendor_id = 10462
product_id = 4607
name = "Microsoft X-Box 360 pad 0"
raw_name = ""
layout = ""
device_kind = "gamepad"
active_binding_preset = ""
binding_presets = []

[[devices]]
id = "1133:50503:Logitech USB Receiver"
vendor_id = 1133
product_id = 50503
name = "G502 X LIGHTSPEED"
raw_name = "Logitech USB Receiver"
layout = ""
device_kind = "mouse"
active_binding_preset = ""
binding_presets = []

[[mappings]]
from = 304

[mappings.to]
type = "key"
code = 33

[[mappings]]
from = 305

[mappings.to]
type = "key"
code = 18

[[mappings]]
from = 306

[mappings.to]
type = "key"
code = 32

[[mappings]]
from = 307

[mappings.to]
type = "key"
code = 17

[[mappings]]
from = 308

[mappings.to]
type = "key"
code = 30

[[mappings]]
from = 309

[mappings.to]
type = "key"
code = 31
